const user = [
  {
    id: 0,
    firstname: 'Brad',
    lastname: 'Gibson',
    age: 33,
    interest: ['Programming & Tech', 'Video & Animation', 'Music & Audio'],
    tags: ['Mixing & Mastering', 'Songwriters', 'WordPress', 'Web Programming'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
    lives: {
      id: 0,
      interest: 'Music & Audio',
      tags: ['Mixing & Mastering', 'Producers & Composers'],
      date: 1625061600,
      length: 2,
      description: 'Learn how to produce your tracks with Ableton.',
    },
  },
  // 1624888800 = timeStamp à convertir, 2 = durée en heure
  {
    id: 1,
    firstname: 'Marian',
    lastname: 'Simonon',
    age: 27,
    interest: ['Programming & Tech', 'Digital Marketing'],
    tags: ['Social Media Marketing', 'Web Programming'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 8,
    photo: 'https://randomuser.me/api/portraits/women/43.jpg',
    lives: [
      {
        id: 0,
        interest: 'Digital Marketing',
        tags: ['Social Media Marketing', 'SEO'],
        date: 1625061600,
        length: 2,
        description: 'Learn SEO in 2 hours.',
      },
      {
        id: 1,
        interest: 'Digital Marketing',
        tags: 'Social Media Marketing',
        date: 1625077800,
        length: 1,
        description: 'A short speak about marketing on social media',
      },
    ],
  },
  {
    id: 2,
    firstname: 'Kyle',
    lastname: 'Wood',
    age: 25,
    interest: ['Programming & Tech', 'Graphics & Design', 'Music & Audio'],
    tags: ['Logo Design', 'Brand Style Guides', 'WordPress', 'Web Programming'],
    online: true,
    mentor: true,
    mentorScore: 5,
    rate: 9,
    photo: 'https://randomuser.me/api/portraits/men/97.jpg',
    lives: {
      id: 0,
      interest: 'Graphics & Design',
      tags: ['Logo Design', 'Brand Style Guides'],
      date: 1625061600,
      length: 2,
      description: 'I will help you to design your perfect logo.',
    },
  },
  {
    id: 3,
    firstname: 'Jennifer',
    lastname: 'Long',
    age: 42,
    interest: ['Programming & Tech', 'Digital Marketing'],
    tags: [
      'Website Builders & CMS',
      'Mobile Apps',
      'E-Commerce development',
      'Web Programming',
    ],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/women/58.jpg',
    lives: {
      id: 0,
      interest: 'Programming & Tech',
      tags: 'E-Commerce development',
      date: 1625068800,
      length: 2,
      description: 'You will be able to launch your own E-Commerce!',
    },
  },
  {
    id: 4,
    firstname: 'Duane',
    lastname: 'Cox',
    age: 37,
    interest: 'Writing & Translation',
    tags: ['Website Content', 'Translation'],
    online: false,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/men/8.jpg',
    lives: {
      id: 0,
      interest: 'Writing & Translation',
      tags: ['Website Content', 'UX Writing'],
      date: 1625072400,
      length: 2,
      description: 'I will help you to create a cool website content.',
    },
  },
  {
    id: 5,
    firstname: 'Norma',
    lastname: 'Richard',
    age: 26,
    interest: ['Writing & Translation', 'Music & Audio'],
    tags: ['Articles & Blog Posts', 'Songwriters', 'Book & eBook writing'],
    online: false,
    mentor: true,
    mentorScore: 5,
    rate: 9,
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
    lives: {
      id: 0,
      interest: 'Writing & Translation',
      tags: ['Articles & Blog Posts', 'Website Content'],
      date: 1625072400,
      length: 3,
      description: 'Write your own articles!',
    },
  },
  {
    id: 6,
    firstname: 'Gordon',
    lastname: 'Binks',
    age: 41,
    interest: ['Programming & Tech', 'Music & Audio'],
    tags: ['Mixing & Mastering', 'WordPress', 'Web Programming'],
    online: true,
    mentor: false,
    mentorScore: 3,
    rate: 8,
    photo: 'https://randomuser.me/api/portraits/men/55.jpg',
    lives: {
      id: 0,
      interest: 'Programming & Tech',
      tags: 'WordPress',
      date: 1624888800,
      length: 2,
      description: 'Become a real expert with WordPress.',
    },
  },
  {
    id: 7,
    firstname: 'Scott',
    lastname: 'Hunt',
    age: 37,
    interest: ['Video & Animation', 'Music & Audio'],
    tags: ['Mixing & Mastering', 'Video Editing'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/men/67.jpg',
    lives: {
      id: 0,
      interest: 'Video & Animation',
      tags: ['Video Editing', 'Short Video Ads'],
      date: 1625077800,
      length: 2,
      description: 'Be able to do your own ads.',
    },
  },
  {
    id: 8,
    firstname: 'Isaac',
    lastname: 'Flemming',
    age: 34,
    interest: ['Graphics & Design', 'Video & Animation'],
    tags: ['Brand Style Guides', 'Logo Design', 'Video Editing'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 13,
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
    lives: {
      id: 0,
      interest: 'Graphics & Design',
      tags: ['Brand Style Guides', 'Logo Design'],
      date: 1625077800,
      length: 2,
      description: 'Give a real and powerfull identity to your brand.',
    },
  },
];

export default user;
