const users = [
  {
    id: 0,
    firstname: 'Brad',
    lastname: 'Gibson',
    age: 33,
    interest: ['Music & Audio', 'Video & Animation', 'Programming & Tech'],
    tags: ['Mixing & Mastering', 'Songwriters', 'WordPress', 'Web Programming'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/men/75.jpg',
  },
  // 1624888800 = timeStamp à convertir, 2 = durée en heure
  {
    id: 1,
    firstname: 'Marian',
    lastname: 'Simonon',
    age: 27,
    interest: ['Programming & Tech', 'Digital Marketing', 'Business'],
    tags: ['Social Media Marketing', 'Web Programming'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 8,
    photo: 'https://randomuser.me/api/portraits/women/43.jpg',
  },
  {
    id: 2,
    firstname: 'Kyle',
    lastname: 'Wood',
    age: 25,
    interest: ['Programming & Tech', 'Graphics & Design', 'Music & Audio'],
    tags: ['Logo Design', 'Brand Style Guides', 'WordPress', 'Web Programming'],
    online: true,
    mentor: true,
    mentorScore: 5,
    rate: 9,
    photo: 'https://randomuser.me/api/portraits/men/97.jpg',
  },
  {
    id: 3,
    firstname: 'Jennifer',
    lastname: 'Long',
    age: 42,
    interest: ['Digital Marketing', 'Programming & Tech', 'Business'],
    tags: [
      'Website Builders & CMS',
      'Mobile Apps',
      'E-Commerce development',
      'Web Programming',
    ],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/women/58.jpg',
  },
  {
    id: 4,
    firstname: 'Duane',
    lastname: 'Cox',
    age: 37,
    interest: ['Writing & Translation'],
    tags: ['Website Content', 'Translation'],
    online: false,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/men/8.jpg',
  },
  {
    id: 5,
    firstname: 'Norma',
    lastname: 'Richard',
    age: 26,
    interest: ['Writing & Translation', 'Music & Audio', 'Lifestyle'],
    tags: ['Articles & Blog Posts', 'Songwriters', 'Book & eBook writing'],
    online: false,
    mentor: true,
    mentorScore: 5,
    rate: 9,
    photo: 'https://randomuser.me/api/portraits/women/26.jpg',
  },
  {
    id: 6,
    firstname: 'Gordon',
    lastname: 'Binks',
    age: 41,
    interest: ['Programming & Tech', 'Music & Audio', 'Lifestyle'],
    tags: ['Mixing & Mastering', 'WordPress', 'Web Programming'],
    online: true,
    mentor: false,
    mentorScore: 3,
    rate: 8,
    photo: 'https://randomuser.me/api/portraits/men/55.jpg',
  },
  {
    id: 7,
    firstname: 'Scott',
    lastname: 'Hunt',
    age: 37,
    interest: ['Programming & Tech', 'Music & Audio', 'Business'],
    tags: ['Mixing & Mastering', 'Video Editing'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 12,
    photo: 'https://randomuser.me/api/portraits/men/67.jpg',
  },
  {
    id: 8,
    firstname: 'Isaac',
    lastname: 'Flemming',
    age: 34,
    interest: ['Graphics & Design', 'Video & Animation', 'Business'],
    tags: ['Brand Style Guides', 'Logo Design', 'Video Editing'],
    online: true,
    mentor: true,
    mentorScore: 4,
    rate: 13,
    photo: 'https://randomuser.me/api/portraits/men/28.jpg',
  },
];

export default users;
